Repository AbdelrahmanEbid/cdm, pull requests merged in 2025-09, with the labels that each got.

#4 [Root] [Release]: Version 1.0.0 – Initial Guide Website Baseline
  .github/workflows/pages.yml
  .gitignore
  01-content
  README.md
  index.html
  package.json
  pnpm-lock.yaml
  public/404.html
  public/favicon.svg
  public/fonts/Cairo-Bold.ttf
  public/fonts/Cairo-Light.ttf
  public/fonts/Cairo-Regular.ttf
  public/fonts/Cairo-SemiBold.ttf
  public/sw.js
  src/main.ts
  src/styles/fonts.css
  src/styles/style.css
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
Labels: release

#5 [Root] [Hotfix]: Add missing CHANGELOG.md for v1.0.0
  CHANGELOG.md
Labels: docs

#6 chore(ci): fix GitHub Actions workflow to install pnpm
  .github/workflows/pages.yml
Labels: CI/CD

#8 [Frontend] [Feat]: Set dark theme as default and adjust header layout
  src/main.ts
  src/styles/style.css
Labels: enhancement

#10 [CI] [Chore]: Split build and deploy in GitHub Actions
  release.sh
Labels: CI/CD
